### ISSUE TITLE
Group 4 - Andreia Agostinho + Paulo Menezes + Tiago Coelho

### ISSUE THREAD

**Issue by AndreiaAgosinho** [sise-cweb/project-template#13]

**Comment by tsCoelho** [comment]
SISE-CWEB GROUP 4

Andreia Agostinho Nº. 4 anagostinho@deloitte.pt
Paulo Menezes Nº. 33 pmenezes@deloitte.pt
Tiago Coelho Nº.40 tiacoelho@deloitte.pt

https://github.com/tsCoelho/project-template
