### ISSUE TITLE
Group 7 - Isabel Pinto + João Silvestre + Rui Alves

### ISSUE THREAD

**Issue by JoaoPedroSilvestre** [sise-cweb/project-template#5]
https://github.com/JoaoPedroSilvestre/project-template

Isabel Pinto nº18 ipinto@deloitte.pt
João Silvestre nº24 josilvestre@deloitte.pt
Rui Alves nº36 rualves@deloitte.pt

**Comment by diasdavid** [comment]
Submissão recebida por email:
![image](https://cloud.githubusercontent.com/assets/1211152/12036615/fbb8e308-ae47-11e5-9fef-6964b087963d.png)
[projectRuiSilvestreIsabel.zip](https://github.com/sise-cweb/project-template/files/74053/projectRuiSilvestreIsabel.zip)
