### ISSUE TITLE
Group 3 - Hugo Santos + João Salvador + Patrícia Ruivo

### ISSUE THREAD

**Issue by santoshugo** [sise-cweb/project-template#7]
https://github.com/santoshugo/project-template.git

Hugo Santos nº16
João Salvador nº22 
Patrícia Ruivo nº32

**Comment by Patriciampruivo** [comment]
PS: O projecto corresponde na sua totalidade ao ultimo commit. Os ficheiros existentes anteriormente não fazem parte.
